### ISSUE TITLE
branchUniversalObject.generateShortUrl never resolves or reject

### ISSUE THREAD

**Issue by thaitanloi365** [BranchMetrics/react-native-branch-deep-linking-attribution#428]
Hi, resolves or reject not fire when called branchUniversalObject.generateShortUrl.
Environment: 
- Platfrom: iOS
- react-native: 0.59.3
- react-native-branch: 2.3.5

Here my code.

try {
      let shareOptions = {
        messageHeader: "Check this out",
        messageBody: "No really, check this out!"
      };
      let linkProperties = {
        feature: "share",
        channel: "facebook",
        campaign: "referral",
        stage: "new user",
        alias: "referralCode"
      };
      let controlParams = {
        $og_title: "TITLE",
        $og_description: "DESCRIPTION",
        $desktop_url: "http://example.com/home",
        $ios_url: "http://example.com/ios",
        $android_url: "http://example.com/android"
      };

      let branchUniversalObject = await branch.createBranchUniversalObject(
        `invitation/${utils.currentUser.id}`,
        {
          locallyIndex: true,
          title: "Cool Content!",
          contentDescription: "Cool Content Description",
          canonicalUrl: "http://example.com/ios",
          contentMetadata: {
            ratingAverage: 4.2,
            customMetadata: {
              prop1: "test",
              prop2: "abc"
            }
          }
        }
      );

      const { url } = await branchUniversalObject.generateShortUrl(
        linkProperties,
        controlParams
      );
      console.log({ url });
      let {
        channel,
        completed,
        error
      } = await branchUniversalObject.showShareSheet(
        shareOptions,
        linkProperties,
        controlParams
      );
    } catch (error) {
      console.log("shareAppDetails error", error);
    }

**Comment by jdee** [comment]
This seems to work fine with `testbed_simple` in the repo. The `webview_example` uses `showShareSheet`, but you could also modify it to call `generateShortUrl`. Perhaps you're missing something in your native code? You can compare these working examples with your app to see what's wrong. Otherwise you could perhaps create a sample app that demonstrates the problem.

Also, we're about to release 3.0.0. All the examples in the repo use the latest version. You should consider updating to 3.0.0. But I doubt that's the problem.

**Comment by javi10823** [comment]
Any update? I have the same issue.

**Comment by dmitryame** [comment]
was this issue ever resolved? I'm running into the same problem and don't know how to approach solving it.
