### ISSUE TITLE
branch io is not opening telegram (in app browser)

### ISSUE THREAD

**Issue by kamal-mobile-dev** [BranchMetrics/react-native-branch-deep-linking-attribution#708]
Hello guys, 
I am facing this issue in some apps for eg. Telegram, Skype.
I read branch io documents but unable to find any hint.
It would be great if anyone can help in this issue.
Thank you.

https://user-images.githubusercontent.com/66624803/168077018-68273a72-c62c-457a-9e78-85334bac04c8.mp4

**Comment by jf-branch** [comment]
Hey @kamal-mobile-dev, many apps actually block Universal Linking and Android App Linking in order to retain the end user in their app, we often see this with Facebook, Instagram, etc. 

What you can do to try to override the blocking by forcing a URI scheme redirect by applying `$uri_redirect_mode:2`as link data when shared through Telegram or Skype. https://help.branch.io/using-branch/docs/creating-a-deep-link#forced-redirections 

Additionally, you could use our deepview feature  on a per link basis, https://help.branch.io/using-branch/docs/deepviews#disable-per-link-deepviews, that allows our determination of if the user has the app or not to forcefully fire a URI scheme redirect.
