### ISSUE TITLE
How to test the getFirstReferringParams in development environment?

### ISSUE THREAD

**Issue by xiaohui-gsv** [BranchMetrics/react-native-branch-deep-linking-attribution#752]
### Describe the feature

When the user clicks the deeplink, and doesn't install the app, it will redirect to the stores and let user installs the app, and when the user opens the app first time, we can get the params from getFirstReferringParams().
My question: is there a way to test the getFirstReferringParams in the development environment? Or we need to publish apps to App store and Google play first, and then we can test the getFirstReferringParams? 
Thank you.

**Comment by jf-branch** [comment]
@xiaohui-gsv You can certainly test in development. Rather than installing from the corresponding App Store. Simply just build the app from your IDE for the first time (meaning installing the app from your IDE). 

Couple things to be aware of. 
- Success rates for Android Deferred Deep Linking (Deep linking on installs) is higher through a Google Play install since we use the install referrer api for deterministic matching. 
- iOS Deferred Deep Linking is a only deterministic when utilizing [NativeLink](https://help.branch.io/using-branch/docs/nativelink-deferred-deep-linking). Unfortunately the apple app store does not have something like the install referrer API. 
- getFirstReferringParams() only returns the referring params for the first session. It does not return the referring params for the most recent session. getLatestReferringParams() returns the current sessions referring parameters.

**Comment by xiaohui-gsv** [comment]
@jf-branch Thank you so much. It works.

**Comment by jf-branch** [comment]
Awesome to hear @xiaohui-gsv!

**Comment by vanLesson** [comment]
@jf-branch  I am currently using React Native version 0.71.3 along with Branch SDK version 5.9.0. I am attempting to get getFirstReferringParams to work in a development environment for a flow where the app is not installed. As part of my investigation, I created a test link. The link behaves as expected when the app is installed. However, when the app is not installed and I click on the link, it takes me to my app's page. After installing my app via IDE, getFirstReferringParams returns empty parameters. I am unsure if this is due to incorrect configuration of NativeLink or if I am misunderstanding the flow. Assistance in understanding and resolving this issue would be appreciated.

**Comment by jf-branch** [comment]
@vanLesson Our support team are best equipped to handle your scenario, they can ask for a bit more details over a private and secured channel to investigate further. You can file a support ticket via: https://help.branch.io/using-branch/page/submit-a-ticket 

However I do want to note a couple things. 

1. IDE builds on Android don't utilize the Google Play Store Install Referrer, which is what Branch uses to provide 100% deterministic Deferred Deep Linking, or Deep Linking through the App Store. 
2. Unfortunately Apple does not offer an install referrer, so the only way we can 100% deterministically Deffered Deep Link is through NativeLink, and this will require you to click on the NativeLink CTA that copies the link to the devices pasteboard and also you will need the code to handle extracting that link copied to the pasteboard. This is valid for an IDE build. More info can be found here: https://help.branch.io/developers-hub/docs/ios-advanced-features#nativelink-deferred-deep-linking

**Comment by vanLesson** [comment]
@jf-branch  Thank you for the response. May I ask another question? On iOS, for an app that is not installed, Safari opens where you have to copy the link and then the app opens. Is this an obligatory step in release builds, or will this screen automatically copy the link and redirect to the app or store on real devices in release builds?

**Comment by jf-branch** [comment]
Excellent question @vanLesson! 

This is the UX for both IDE and Release builds of NativeLink when App is not installed. 

This was a conscious decision on our end. We wanted to foster Apple's practices and preferences in allowing end user consent and providing transparency and awareness as to what is going on for the end user. We felt if we were to automate it, the UX would feel "forced" and

**Comment by vanLesson** [comment]
@jf-branch Thanks for the answer)
