### ISSUE TITLE
Deferred deep links not working reliably on iOS

### ISSUE THREAD

**Issue by michaelbayerle** [BranchMetrics/react-native-branch-deep-linking-attribution#876]
### Describe the bug

`params` in `OnOpenComplete` do not contain branch link, i.e. `+clicked_branch_link=false`. This is only happening for deferred deep links and sometimes when the app is cold started. When the app is backgrounded, everything works as expected.

The behavior is somewhat random. Sometimes the `params` contain the branch link, sometimes not. When making a debug build in Xcode the chances of `params` containing the branch link are higher than when making a release build.

Since the behavior is somewhat random, I was assuming that a race condition could be the reason for the unstable behavior. I tried setting `"deferInitForPluginRuntime": true` in `branch.json` but this doesn't seem to help.

Native links on iOS are enabled.

### Steps to reproduce

1. Click deep link
2. Get redirected to Browser
3. Click Get the App
4. Install App from App Store (or build and deploy app from Xcode)
5. Do not receive params

### Expected behavior

Receive `params` in `onOpenComplete`.

### SDK Version

2.2.0

### Make and Model

iPhone 14 Pro (among others)

### OS

iOS 16.3.1

### Additional Information/Context

in `onOpenStart`, `cachedInitialEvent=undefined`. The `uri` is non-empty and reads `io.<app-name>.<app-name>://google/link?request_ip_version=IP%5FV6&match_message=No%20pre%2Dinstall%20link%20matched%20for%20this%20device%2E`. I don't really know how to interpret this.

**Comment by michaelbayerle** [comment]
I just figured out that if I wrap my `branch.subscribe` in a `setTimeout()`, the parameters get passed correctly:
```
useEffect(() => {
    setTimeout(() =>{
        branch.subscribe(...)
    }, 2000);
}, []);
```
Any idea what's going on here?

**Comment by brycnguyen** [comment]
I am noticing a similar issue where my params are not being passed when the default browser for the user is chrome on iOS

**Comment by NidhiDixit09** [comment]
Thank for reporting the issue. An internal ticket is created for this issue.

**Comment by tomoakley** [comment]
branch.subscribe seems to get re-registered when the app state changes from background/inactive to foreground. From my debugging/experience it seems like that when a system prompt appears e.g Face ID or the notification permissions (causing the app state to go from foreground to inactive for a few seconds until the prompt is cleared), it gets a new subscribe listener without the original data. From some logging I added, when the app first starts up and branch.subscribe is added, the data is there but then when it gets re-registered, it gets lost/forgotten. I guess a workaround is to persist it somehow. We see this specifically on deferred deep links because the user gets the app, logs in and sets up Face ID/notifications. With users who already have the app, they are less likely to get a system prompt like this so the subscribe listener is more reliable.

**Comment by dan-herasymov** [comment]
For me it was Firebase Dynamic Links I used before Branch. I had to remove FDL completely from the project to make branch.io links start working properly.

As result instead of wrong `<app-name>://google/link?...` as initial uri I get my referring link in `params['~referring_link']` as initial link after installation

**Comment by echo-branch** [comment]
@michaelbayerle 
I think @dan-herasymov is on the right track. 

The link in the original description looks like a Google URI and not a Universal Link or a Branch Link. The Google SDK used to swizzle the AppDelegate APIs so they get first shot at handling them. That could be causing issue with us getting the link data.

https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in

**Comment by michaelbayerle** [comment]
Thanks for the pointer @dan-herasymov. Removing FB dynamic links helped. @echo-branch it might be a good idea to point this out in some installation instructions, since a lot of users will be transitioning from FB to branch.
